# Generated by Django 4.2.13 on 2024-07-09 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer_cod',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Номер варианта ответа'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='f_check',
            field=models.BooleanField(blank=True, null=True, verbose_name='Правильный ли ответ'),
        ),
        migrations.AlterField(
            model_name='group',
            name='amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='app',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='group',
            name='parent_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Группа вопросов'),
        ),
        migrations.AlterField(
            model_name='group',
            name='sort_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='theme_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='testing.theme'),
        ),
        migrations.AlterField(
            model_name='group',
            name='type_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='namesprav',
            name='is_active',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='namesprav',
            name='is_change',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='namesprav',
            name='item_name_cod',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Кол-во вопросов в тесте'),
        ),
        migrations.AlterField(
            model_name='test',
            name='f_check',
            field=models.BooleanField(blank=True, null=True, verbose_name='Правильный ли ответ'),
        ),
        migrations.AlterField(
            model_name='test',
            name='n_q',
            field=models.IntegerField(blank=True, null=True, verbose_name='Номер вопроса в тесте'),
        ),
        migrations.AlterField(
            model_name='testperson',
            name='amount_time',
            field=models.FloatField(blank=True, null=True, verbose_name='Среднее время'),
        ),
        migrations.AlterField(
            model_name='testperson',
            name='is_delete',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='testperson',
            name='is_passed',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='Кол-во удачных прохождений теста'),
        ),
        migrations.AlterField(
            model_name='testperson',
            name='log_test',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Логин для теста'),
        ),
        migrations.AlterField(
            model_name='testperson',
            name='n_break_quest',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='testperson',
            name='n_try',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Кол-во попыток'),
        ),
        migrations.AlterField(
            model_name='testperson',
            name='passw_test',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='testperson',
            name='person_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='testperson',
            name='phone',
            field=models.CharField(blank=True, default='0', max_length=63, null=True, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='testperson',
            name='result_person',
            field=models.FloatField(blank=True, null=True, verbose_name='Результат тестирования попытка 1'),
        ),
        migrations.AlterField(
            model_name='testperson',
            name='result_person2',
            field=models.FloatField(blank=True, null=True, verbose_name='Результат тестирования попытка 2'),
        ),
        migrations.AlterField(
            model_name='testperson',
            name='time_str',
            field=models.CharField(blank=True, max_length=31, null=True, verbose_name='Время тестирования попытка 1'),
        ),
        migrations.AlterField(
            model_name='testperson',
            name='time_str2',
            field=models.CharField(blank=True, max_length=31, null=True, verbose_name='Время тестирования попытка 2'),
        ),
        migrations.AlterField(
            model_name='testperson',
            name='use_try',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Кол-во использованых попыток'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='group_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='testing.group'),
        ),
    ]
